services:
  factorio:
    container_name: factorio
    image: ghcr.io/williamweatherholtz/factorio:stable
    restart: unless-stopped
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    env_file:
      - .env
    volumes:
      - ./config:/factorio/config              # server-settings, map-*, rconpw, lists, server-id
      - ./saves:/factorio/saves                # back these up
      - ./mods:/factorio/mods                  # add/remove mods from the host
      - ./scenarios:/factorio/scenarios
      - ./script-output:/factorio/script-output

    # Uncomment to enable autoupdate via watchtower
    #labels:
    #  - com.centurylinklabs.watchtower.enable=true
    #  - com.centurylinklabs.watchtower.scope=factorio
    #  - com.centurylinklabs.watchtower.lifecycle.pre-update="/players-online.sh"

  # Uncomment to use watchtower for updating the factorio container
  # Full documentation: https://github.com/containrrr/watchtower
  #watchtower:
  #  container_name: watchtower_factorio
  #  image: ghcr.io/nicholas-fedor/watchtower:latest
  #  restart: unless-stopped
  #  volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  #  environment:
  #    - WATCHTOWER_TIMEOUT=30s
  #    - WATCHTOWER_LABEL_ENABLE=true
  #    - WATCHTOWER_POLL_INTERVAL=3600
  #    - WATCHTOWER_LIFECYCLE_HOOKS=true
  #    - WATCHTOWER_SCOPE=factorio
  #  labels:
  #    - com.centurylinklabs.watchtower.scope=factorio
